### ISSUE TITLE
Add a equation editor to TinyMCE.Blazor

### ISSUE THREAD

**Issue by subhasis68** [tinymce/tinymce-blazor#75]
I am using TinyMCE.Blazor in a Blazor Server Project with razor component.

It works fine.

However, I need to add an equation editor in the TinyMCE.Blazor component.

How do I do that.

**Comment by spocke** [comment]
Since this is just a wrapper around the TinyMCE project we would need to treat this as a feature request Equations is on this features and idea page so you can cast your vote there on it getting added: https://www.tiny.cloud/roadmap/ I'm closing this ticket since it's not a feature request for the actual Blazor integration.
